### ISSUE TITLE
Please port to OSX

### ISSUE THREAD

**Issue by rw** [Project-10/DGM#3]
I'm excited to try this library!

I see the forum posts and Github issues asking for this. I don't have Windows, so my options are limited.

Compiling manually with

```
clang++ -std=c++11 -libstd=libc++ -fms-compatibility -fms-compatibility-version=19.00.23506 -fms-extensions
```

helps but is not enough.

Please port this to run on other operating systems :-)

**Comment by ereator** [comment]
Dear Robert,

thank you for your interest to the library and sorry for the long reply.

We do not plan porting DGM library to other operating systems in the nearest future. However, starting from [version 1.5.0](https://github.com/Project-10/DGM/releases/tag/v.1.5.0-alpha) we switched to using [CMake](https://cmake.org/), which among other things allows generating projects for Mac OS. Most probably, you will need to modify _CMakeLists.txt_ files and disable PPL support, but it should help to build the library for OSX.

Sorry, that I cant help you more at this moment.

**Comment by ereator** [comment]
Dear Robert,

I am glad to tell you that we have started porting the DGM library to OSX. Starting from the version 1.6 DGM library will be compiled in Windows (MSVC) and MacOS (xCode). The current beta version of the DGM v.1.6.0 might be built with CMake xCode. In order to that, please disable the support of PPL, AMP, Sherwood and OpenGL in CMake. 

Further step-by-step porting will be done in the MacOS branch.

**Comment by ereator** [comment]
@rw The library is ported to OSX. Please close this issue.
